# Generated by Django 4.2 on 2023-04-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
